service: github-board-slack-notifications

plugins:
  - serverless-plugin-typescript

variablesResolutionMode: 20210326

provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  architecture: arm64
  deploymentMethod: direct

functions:
  handler:
    handler: src/handler.run
    url: true
    maximumRetryAttempts: 0
    timeout: 5
    memorySize: 128
    environment: ${file(./variables.yml)}
